### ISSUE TITLE
cbwm模型

### ISSUE THREAD

**Issue by jin1ming** [SugarRuy/HashStash#1]
您好，请问cbwm所使用的模型从哪下载呢？

**Comment by SugarRuy** [comment]
Please read the README file. 

Here is the [link](https://drive.google.com/open?id=1d_jBCcMfKgJ_dKfWAlwDxQXQGb0r2HqI) in google drive for models we use and the Hash codes. The **snapshot** sub-folder is for the model files. 

**You can also train a model by yourself.**

```myTrain.py ```  and ```myExtractCodeLabel.py``` would be helpful for you if you want to do so.

**Comment by jin1ming** [comment]
ok,thanks!
